"""日麻对局内核（牌、牌山、状态机等）。大模型调用见 ``llm`` 包。"""

from kernel.hand import (
    Meld,
    MeldKind,
    add_tile,
    concealed_from_iterable,
    concealed_total,
    meld_tile_count,
    remove_tile,
    remove_tiles,
    tiles_from_concealed_and_melds,
    triplet_key,
    validate_hand_package,
    validate_meld_shape,
    validate_tile_conservation,
)
from kernel.table import (
    DEFAULT_STARTING_POINTS,
    RIICHI_STICK_POINTS,
    MatchPreset,
    PrevailingWind,
    RoundNumber,
    TableSnapshot,
    initial_table_snapshot,
    seat_wind_rank,
    validate_table_snapshot,
)
from kernel.tiles import Suit, Tile, build_deck, shuffle_deck
from kernel.wall import (
    DEAD_WALL_SIZE,
    INDICATOR_COUNT,
    LIVE_WALL_SIZE,
    RINSHAN_COUNT,
    WALL_SIZE,
    DeadWall,
    WallSplit,
    split_wall,
)

__all__ = [
    "DEFAULT_STARTING_POINTS",
    "DEAD_WALL_SIZE",
    "DeadWall",
    "INDICATOR_COUNT",
    "LIVE_WALL_SIZE",
    "MatchPreset",
    "Meld",
    "MeldKind",
    "PrevailingWind",
    "RIICHI_STICK_POINTS",
    "RINSHAN_COUNT",
    "RoundNumber",
    "Suit",
    "TableSnapshot",
    "Tile",
    "WALL_SIZE",
    "WallSplit",
    "add_tile",
    "build_deck",
    "concealed_from_iterable",
    "concealed_total",
    "initial_table_snapshot",
    "meld_tile_count",
    "remove_tile",
    "remove_tiles",
    "seat_wind_rank",
    "shuffle_deck",
    "split_wall",
    "tiles_from_concealed_and_melds",
    "triplet_key",
    "validate_hand_package",
    "validate_meld_shape",
    "validate_table_snapshot",
    "validate_tile_conservation",
]
