"""日麻对局内核（牌、牌山、状态机等）。大模型调用见 ``llm`` 包。"""

from kernel.api import LegalAction, Observation, legal_actions, observation
from kernel.deal import (
    FIRST_DORA_INDICATOR_INDEX,
    INITIAL_DEAL_TILES,
    LIVE_WALL_AFTER_DEAL,
    BoardState,
    RiverEntry,
    TurnPhase,
    assert_wall_is_standard_deck,
    build_board_after_split,
    validate_board_state,
)
from kernel.engine import (
    Action,
    ActionKind,
    ApplyOutcome,
    EngineError,
    GamePhase,
    GameState,
    IllegalActionError,
    apply,
    initial_game_state,
)
from kernel.hand import (
    Meld,
    MeldKind,
    add_tile,
    concealed_from_iterable,
    concealed_total,
    meld_tile_count,
    remove_tile,
    remove_tiles,
    tiles_from_concealed_and_melds,
    triplet_key,
    validate_hand_package,
    validate_meld_shape,
    validate_tile_conservation,
)
from kernel.play import apply_discard, apply_draw
from kernel.table import (
    DEFAULT_STARTING_POINTS,
    RIICHI_STICK_POINTS,
    MatchPreset,
    PrevailingWind,
    RoundNumber,
    TableSnapshot,
    initial_table_snapshot,
    seat_wind_rank,
    validate_table_snapshot,
)
from kernel.tiles import Suit, Tile, build_deck, shuffle_deck
from kernel.wall import (
    DEAD_INDICATOR_STOCK,
    DEAD_WALL_SIZE,
    INDICATOR_COUNT,
    LIVE_WALL_SIZE,
    RINSHAN_COUNT,
    WALL_SIZE,
    DeadWall,
    WallSplit,
    split_wall,
)

__all__ = [
    "Action",
    "ActionKind",
    "ApplyOutcome",
    "BoardState",
    "RiverEntry",
    "TurnPhase",
    "DEFAULT_STARTING_POINTS",
    "DEAD_INDICATOR_STOCK",
    "DEAD_WALL_SIZE",
    "DeadWall",
    "EngineError",
    "FIRST_DORA_INDICATOR_INDEX",
    "INDICATOR_COUNT",
    "INITIAL_DEAL_TILES",
    "LIVE_WALL_AFTER_DEAL",
    "LIVE_WALL_SIZE",
    "GamePhase",
    "GameState",
    "IllegalActionError",
    "LegalAction",
    "MatchPreset",
    "Meld",
    "MeldKind",
    "Observation",
    "PrevailingWind",
    "RIICHI_STICK_POINTS",
    "RINSHAN_COUNT",
    "RoundNumber",
    "Suit",
    "TableSnapshot",
    "Tile",
    "WALL_SIZE",
    "WallSplit",
    "add_tile",
    "apply",
    "apply_discard",
    "apply_draw",
    "assert_wall_is_standard_deck",
    "build_board_after_split",
    "build_deck",
    "concealed_from_iterable",
    "concealed_total",
    "initial_game_state",
    "initial_table_snapshot",
    "legal_actions",
    "meld_tile_count",
    "observation",
    "remove_tile",
    "remove_tiles",
    "seat_wind_rank",
    "shuffle_deck",
    "split_wall",
    "tiles_from_concealed_and_melds",
    "triplet_key",
    "validate_board_state",
    "validate_hand_package",
    "validate_meld_shape",
    "validate_table_snapshot",
    "validate_tile_conservation",
]
